---
AWSTemplateFormatVersion: 2010-09-09


Description: Event handler for app installations


Metadata:
   AWS::CloudFormation::Interface:
      ParameterGroups:
         -
            Label: Lambda package
            Parameters:
               - LambdaPackagesBucket
               - LambdaFunctionPackageObjectVersion

      ParameterLabels:
         LambdaPackagesBucket:
            default: Bucket
         LambdaFunctionPackageObjectVersion:
            default: Object version


Parameters:
   LambdaPackagesBucket:
      Description: Name of the S3 bucket that contains the Lambda deployment package.
      Type: String

   LambdaFunctionPackageObjectVersion:
      Description: ID of the version of the S3 object to use as Lambda deployment package.
      Type: String


Resources:
   CloudFormationRole:
      Type: AWS::IAM::Role
      Properties: {
         AssumeRolePolicyDocument: {
            Version: 2012-10-17,
            Statement: [
               {
                  Principal: {
                     Service: cloudformation.amazonaws.com,
                  },
                  Action: [
                     'sts:AssumeRole',
                  ],
                  Effect: Allow,
               },
            ],
         },
         Policies: [
            {
               PolicyName: management,
               PolicyDocument: {
                  Version: 2012-10-17,
                  Statement: [
                     {
                        Sid: SNS,
                        Action: [
                           'sns:CreateTopic',
                           'sns:DeleteTopic',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:*',
                           },
                        ],
                        Effect: Allow,
                     },
                  ],
               },
            },
         ],
      }

   FunctionRole:
      Type: AWS::IAM::Role
      Properties: {
         AssumeRolePolicyDocument: {
            Version: 2012-10-17,
            Statement: [
               {
                  Principal: {
                     Service: lambda.amazonaws.com,
                  },
                  Action: [
                     'sts:AssumeRole',
                  ],
                  Effect: Allow,
               },
            ],
         },
         ManagedPolicies: [
            {
               'Fn::Sub': 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
            },
         ],
         Policies: [
            {
               PolicyName: installation-management,
               PolicyDocument: {
                  Version: 2012-10-17,
                  Statement: [
                     {
                        Action: [
                           'cloudformation:CreateStack',
                           'cloudformation:DeleteStack',
                           'cloudformation:DescribeStacks',
                           'cloudformation:UpdateStack',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': 'arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/installation-*/*',
                           },
                        ],
                        Effect: Allow,
                     },
                     {
                        Action: [
                           'iam:PassRole',
                        ],
                        Resource: [
                           {
                              'Fn::GetAtt': [
                                 CloudFormationRole,
                                 Arn,
                              ],
                           },
                        ],
                        Condition: {
                           StringEquals: {
                              'iam:PassedToService': cloudformation.amazonaws.com,
                           },
                        },
                        Effect: Allow,
                     },
                  ],
               },
            },
         ],
      }

   Function:
      Type: AWS::Lambda::Function
      Properties: {
         Code: {
            S3Bucket: {
               Ref: LambdaPackagesBucket,
            },
            S3Key: functions/events/installation.zip,
         },
         Environment: {
            Variables: {
               CLOUDFORMATION_ROLE: {
                  Ref: CloudFormationRole,
               },
            },
         },
         Handler: index.handler,
         Layers: [
            #{
            #   Ref: OctokitLibrary,
            #},
         ],
         MemorySize: '128',
         Role: {
            'Fn::GetAtt': [
               FunctionRole,
               Arn,
            ]
         },
         Runtime: ruby2.5,
      }


Outputs:
   FunctionName:
      Description: Name of the Lambda function.
      Value:
         Ref: Function
