---
AWSTemplateFormatVersion: 2010-09-09


Description: Client installation


Metadata:
   AWS::CloudFormation::Interface:
      ParameterGroups:
         -
            Label: Integration
            Parameters:
               - PipelineStackNotificationFunction
         -
            Label: Client
            Parameters:
               - ClientAccount
               - ClientCloudFormationRole

      ParameterLabels:
         ClientAccount:
            default: Account ID
         ClientCloudFormationRole:
            default: CloudFormation role
         PipelineStackNotificationFunction:
            default: Lambda function ARN


Parameters:
   ClientAccount:
      Description: ID of the client's AWS account.
      Type: String

   ClientCloudFormationRole:
      Description: Name of the client's IAM role for CloudFormation.
      Type: String

   PipelineStackNotificationFunction:
      Description: Name of the Lambda function to handle CloudFormation notifications.
      Type: String


Resources:
   # When a new branch is created, a new pipeline must be deployed
   # using CloudFormation. The integration has CloudFormation send
   # status notifications to this SNS topic.
   PipelineStackNotificationTopic:
      Type: AWS::SNS::Topic
      Properties: {
      }

   PipelineStackNotificationTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties: {
         Topics: [
            {
               Ref: PipelineStackNotificationTopic,
            },
         ],
         PolicyDocument: {
            Statement: [
               {
                  Principal: {
                     AWS: [
                        {
                           'Fn::Sub': 'arn:${AWS::Partition}:iam::${ClientAccount}:role/${ClientCloudFormationRole}',
                        },
                     ],
                  },
                  Action: [
                     'sns:Publish',
                  ],
                  Resource: [
                     '*',
                  ],
                  Condition: {
                     StringEquals: {
                        'aws:SourceAccount': {
                           Ref: ClientAccount,
                        },
                     },
                  },
                  Effect: Allow,
               },
            ],
         },
      }

   PipelineStackNotificationSubscription:
      Type: AWS::SNS::Subscription
      Properties: {
         TopicArn: {
            Ref: PipelineStackNotificationTopic,
         },
         Protocol: lambda,
         Endpoint: {
            'Fn::Sub': 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${PipelineStackNotificationFunction}',
         },
      }


Outputs:
   Topic:
      Description: 'ID of the SNS topic for the client.'
      Value:
         Ref: PipelineStackNotificationTopic
