---
AWSTemplateFormatVersion: 2010-09-09


Description: 'webpipe source integration for GitHub'


Resources:
   LambdaLogsPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties: {
         Description: Let Lambda functions output CloudWatch logs,
         PolicyDocument: {
            Version: 2012-10-17,
            Statement: [
               {
                  Action: [
                     'logs:CreateLogGroup',
                  ],
                  Resource: [
                     '*',
                  ],
                  Effect: Allow,
               },
               {
                  Action: [
                     'logs:CreateLogStream',
                     'logs:PutLogEvents',
                  ],
                  Resource: [
                     {
                        'Fn::Sub': 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*',
                     },
                     {
                        'Fn::Sub': 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*:*',
                     },
                  ],
                  Effect: Allow,
               },
            ],
         },
      }
