---

template_path: webhook.yaml

parameters:
   ApiId: !stack_output amber/gateway.yaml::ApiId
   LambdaPackagesBucket: !stack_output amber/lambda_packages_bucket.yaml::LambdaPackagesBucket
   LambdaFunctionPackageObjectVersion: !file_contents /lambda/functions/webhook.txt

#hooks:
#   before_create:
#      - >-
#         !cmd
#         s3am
#         add
#         --bucket !stack_output lambda_packages_bucket::LambdaPackagesBucket
#         --object-key /functions/webhook.zip
#         lambda/functions/webhook.tar
#         lambda/functions/webhook.zip
#         > lambda/functions/webhook.txt
#   before_update:
#      # FIXME
#      - SAME AS ABOVE
